### ISSUE TITLE
Mobile Enviroment

### ISSUE THREAD

**Issue by nsalin** [robertiagar/robertiagar.com#42]
Hi Robert, today I accessed your (WIP) blog from my Samsung Galaxy S3 and it doesn't scale for mobile devices, please review your code and announce me when you improve your blog. PS: I like it, and it was a new experience for me  to see your new development technologies.

**Comment by robertiagar** [comment]
Could you please provide a screenshot and more details of which browser (and version) you used?

**Comment by nsalin** [comment]
I'm sorry Robert, I forgot to upload the screenshot,down you'll find the screenshot, and I used the latest version of Google Chrome. I also tested your blog on my lenovo tablet, you'll find the screenshot below.
S3 screenshot ![2014-09-01 19 51 19](https://cloud.githubusercontent.com/assets/8618602/4111569/3f1e4160-320c-11e4-8a61-c0d51fbe001d.png)
Lenovo screenshot 
![2014-09-01 22 24 45](https://cloud.githubusercontent.com/assets/8618602/4111634/eafde7fa-320d-11e4-8a1f-8a6ae92f8744.png)

**Comment by robertiagar** [comment]
I'll get to work on this as soon as I can. Thank you!

**Comment by robertiagar** [comment]
partially fixed in pull request #44

**Comment by robertiagar** [comment]
fully fixed will pull request #45 

could you please verify?
