### ISSUE TITLE
Add exclude list _config.yml

### ISSUE THREAD

**Issue by CGarces** [robertiagar/robertiagar.com#72]
Hi!

I'm using your git repository as inspiration for my own blog.

I have noticed that some unneeded file are published

Consider add this lines to your _config.yml

```
exclude: 
 - README.md
 - Gemfile
 - Gemfile.lock
```

**Comment by robertiagar** [comment]
Can you create a Pull Request with this fix? I'll gladly accept it :)

Thanks for noticing

**Comment by CGarces** [comment]
See https://github.com/robertiagar/robertiagar.com/pull/73

Note that the modification is untested, but a similar one works on my site.
Also I have added CNAME, I assume that not should be published.

**Comment by robertiagar** [comment]
The CNAME is being used by the DNS to link the github.io page to my domain.

**Comment by robertiagar** [comment]
It works... Thank you for the help! :)
